# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Install sqlite3 CLI
RUN apt-get update \
    && apt-get install -y --no-install-recommends sqlite3 \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements and source
COPY requirements.txt setup.py setup_law_office.py server.py ./
COPY src ./src
COPY database ./database

# Install Python dependencies and the package
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir . \
    # Initialize SQLite database using schema.sql
    && mkdir -p database \
    && sqlite3 database/law_office.db < database/schema.sql

# Expose default port if any (MCP uses stdio, so none)
# Default command
CMD ["python3", "server.py", "--db-path", "database/law_office.db"]
